insert into persona (nombre,apellido,fecha_nacimiento) values ('Alejandra','Juarez','02/03/2022');
insert into menu (Opcion_menu) values ('login');
insert into tipo_usuario (tipo_usuario) values('Administrador');
insert into rol (nombre_rol) values ('Empleado');
insert into rol_tipo_usuario (id_rol,id_tipo_usuario) values(6,16);
insert into cliente (idpersona,id_tipo_usuario,fecha_alta,usuario_cliente,contrasena) values(1,16,'02/05/2022','Juan','remember123');
insert into correo (idpersona,idcliente,email) values(1,1,'correogenerico@gmail.com');
insert into telefono (idpersona,idcliente,numero) values (1,1,'52304059');
insert into empleado (id_tipo_usuario,idpersona,fecha_ingreso,fecha_egreso,usuario,contrasena) values(1,1,'02/04/2000','17/11/2022','juancho','contrasena');
insert into tipo_documento (nacionalidad,pasaporte,licencia) values ('Guatemalteca','Pasaporte Ordinario','A');
insert into documento_persona (id_tipopersona,idPersona) values (2,1);
insert into estado(disponibilidad) values ('Disponible');
insert into estado(disponibilidad) values ('Reservado');
insert into categorias(nombre_categoria) values ('Apartamento');
insert into categorias(nombre_categoria) values ('Casa');
insert into categorias(nombre_categoria) values ('Casa 2 niveles');
insert into categorias(nombre_categoria) values ('local');
insert into categorias(nombre_categoria) values ('oficina');
insert into departamento(departamento) values ('Guatemala');
insert into municipio(id_departamento,municipio) values (1,'Guatemala');
insert into municipio(id_departamento,municipio) values (1,'Villa Nueva');
insert into zona (zona) values ('zona 12');
insert into zona (id_municipio,zona) values (2,'zona 3');
insert into zona (id_municipio,zona) values (1,'zona 10');
insert into aldeas_caserio(id_municipio,aldea_caserio) values (2,'Barcenas');
insert into colonia (id_zona,nom_colonias) values (1,'Reformita');
insert into zona_geografica(id_municipio,id_aldea) values (2,1);
insert into zona_geografica(id_municipio,id_colonias) values (1,1);
insert into inmueble(idestado_inmueble,idcategoria,id_departamento,nombre_inmueble,descripcion,capacidad,direccion,url_imagen) values (1,1,1,'Apartamento zona 10','Apartamento ubicado en segundo nivel, privilegiado con amplio Jardín, pérgola eléctrica, excelente iluminación y ventilación, habitación Master con tv',4,'Zona 10, Guatemala, Ciudad Guatemala, Guatemala','https://http2.mlstatic.com/D_NQ_NP_2X_945833-MGT52419975509_112022-F.webp');
insert into renta(idcliente,idestado_inmueble,idinmueble,fecha_renta,tiempo_renta_reserva,valor) values (1,1,1,'20/11/2022','30/11/2022',100);