create or replace  TRIGGER TGR_PERSONA
BEFORE INSERT ON PERSONA REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT TEST_SEQ12.NEXTVAL INTO :New.IDPERSONA  FROM DUAL;
END;

create or replace  TRIGGER TGR_CLIENTE
BEFORE INSERT ON CLIENTE REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT TEST_SEQ2.NEXTVAL INTO :New.IDCLIENTE  FROM DUAL;
END;
create or replace  TRIGGER TGR_CORREO
BEFORE INSERT ON CORREO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT TEST_SEQ3.NEXTVAL INTO :New.IDCORREO  FROM DUAL;
END;

create or replace  TRIGGER TGR_TELEFONO
BEFORE INSERT ON TELEFONO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT TEST_SEQ19.NEXTVAL INTO :New.IDTELEFONO  FROM DUAL;
END;

create or replace  TRIGGER TGR_TIPOUSUARIO
BEFORE INSERT ON TIPO_USUARIO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT TEST_SEQ21.NEXTVAL INTO :New.ID_TIPO_USUARIO FROM DUAL;
END;

create or replace  TRIGGER TGR_ROL
BEFORE INSERT ON ROL REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT TEST_SEQ18.NEXTVAL INTO :New.ID_ROL FROM DUAL;
END;

create or replace  TRIGGER TGR_ROL_TIPO_USUARIO
BEFORE INSERT ON ROL_TIPO_USUARIO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT TEST_SEQ17.NEXTVAL INTO :New.ID_ROL_TIPO_USUARIO FROM DUAL;
END;

create or replace  TRIGGER TGR_EMPLEADO
BEFORE INSERT ON EMPLEADO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN
    SELECT TEST_SEQ6.NEXTVAL INTO :New.ID_EMPLEADO FROM DUAL;
END;

